name: s3 react app
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 's3-react/**'
defaults:
  run:
    working-directory: s3-react
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: aws s3 sync build s3://codehance-react-app
